class Config:
    BASEURL = "https://thinking-tester-contact-list.herokuapp.com/"
    LOGIN_USERNAME = "James2334@sharklasers.com"
    LOGIN_PASSWORD = "Abcd1234#"
    FIRSTNAME = "JOHN"
    LASTNAME = "HASSAN"
    EMAIL = "jamesg22@sharklasers.com"
    PASSWORD = "Abcd1234#"
    CONTACT_FIRSTNAME = "James"
    CONTACT_LASTNAME = "Bolton"
    CONTACT_DATE_OF_BIRTH = "2023/02/02"
    CONTACT_EMAIL = "bolton22@sharklasers.com"
    CONTACT_PHONE = "09157888392"
    CONTACT_ADDRESS_1 = "Lagos"
    CONTACT_ADDRESS_2 = "VI"
    CONTACT_CITY = "Lagos"
    CONTACT_STATE = "Lagos"
    CONTACT_POSTCODE = "10002"
    CONTACT_COUNTRY = "Nigeria"

